### ISSUE TITLE
Crash In Flowey Hangout 1 

### ISSUE THREAD

**Issue by SkyBlueSiha** [undertale-dating-sim/dating-sim-demo-2#58]
When Clicking Lets Play A Game (or something like that) this happens
![crash](https://user-images.githubusercontent.com/20992627/27497328-a28e48b2-581f-11e7-867d-2c285a6d84c2.JPG)

**Comment by CFWebb** [comment]
@SkyBlueSiha Thanks for the screenshot! <3 a quick find/replace and this is fixed and waiting to be merged in! Gonna close this issue now
