### ISSUE TITLE
Repeating lines with Toriel

### ISSUE THREAD

**Issue by Aumaris** [undertale-dating-sim/dating-sim-demo-2#59]
When initially chatting with Toriel, she says the line "Hello, dear. Can I help you?" twice. It's both odd and repetitive.

**Comment by CFWebb** [comment]
@Aumaris So I took out the first line that she says before the menu, and now she says it with the menu open. If you figure it should be the other way around just lemme know and I'll switch it. For now I'll close this issue <3
