### ISSUE TITLE
The Warping Frisk

### ISSUE THREAD

**Issue by Aumaris** [undertale-dating-sim/dating-sim-demo-2#60]
Frisk's sprites seem to 'warp' for a lack of better words while you talk to them. Not sure if that's a permanent thing, or what can be done about it....idk I'm just confused XD

big frisk : https://puu.sh/wsuj8/5b3c9454ce.jpg
smol frisk : http://puu.sh/wsujT/6344e3b70e.jpg

This one seems more like something that the art team would need to look at though if I'm not mistaken... but I'm not sure honestly.

**Comment by CFWebb** [comment]
Wilson fixed this yesterday <3
